svat/apps/my_admin/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # Dashboard
    path('dashboard', views.index, name='admin.dashboard'),
    path('login', views.handle_login, name='admin.login'),
    path('logout', views.handle_logout, name='admin.logout'),
    path('403', views.handle403, name='admin.403'),


    # User
    path('user', views.user, name='admin.user'),
    path('getAllUser', views.get_all_user, name='admin.get_all_user'),
    path('createUser', views.create_user, name='admin.create_user'),
    path('updateUser', views.update_user, name='admin.update_user'),
    path('deleteUser', views.delete_user, name='admin.delete_user'),

    # Product category
    path('product_category', views.product_category, name='admin.product_category'),
    path('getAllProductCategory', views.get_all_product_category, name='admin.get_all_product_category'),
    path('createProductCategory', views.create_product_category, name='admin.create_product_category'),
    path('updateProductCategory', views.update_product_category, name='admin.update_product_category'),
    path('deleteProductCategory', views.delete_product_category, name='admin.delete_product_category'),

    # Article
    path('getArticles', views.get_articles, name='admin.get.article'),
    path('article', views.article_index, name='admin.article'),
    path('article/<int:id>', views.article_edit, name='admin.article.get.edit'),
    path('article/edit', views.article_post_edit, name='admin.article.post.edit'),
    path('article/new', views.article_store, name='admin.article.get.store'),
    path('article/store', views.article_post_store, name='admin.article.post.store'),
    path('uploads', views.uploads, name='admin.upload'),

    # Product
    path('getProducts', views.get_products, name='admin.get.product'),
    path('product', views.product_index, name='admin.product'),
    path('product/<int:id>', views.product_edit, name='admin.product.get.edit'),
    path('product/new', views.product_store, name='admin.product.get.store'),
    path('product/edit', views.product_post_edit, name='admin.product.post.edit'),
    path('product/store', views.product_post_store, name='admin.product.post.store'),

    #Article Category
    path('article_category', views.article_category, name='admin.article_category'),
    path('getAllArticleCategory', views.get_all_article_category, name='admin.get_all_article_category'),
    path('createArticleCategory', views.create_article_category, name='admin.create_article_category'),
    path('updateArticleCategory', views.update_article_category, name='admin.update_article_category'),
    path('deleteArticleCategory', views.delete_article_category, name='admin.delete_article_category'),

    # Order
    path('order', views.order_index, name='admin.order'),
    path('getAllOrder', views.get_all_order, name='admin.get_all_order'),
    path('updateOrder', views.update_order, name='admin.update_order'),
    path('getDetailOrder', views.get_detail_order, name='admin.get_detail_order'),
    path('getOrderInProgress', views.get_order_in_progress, name='admin.get_order_in_progress'),
    path('sendEmailOrderInProgress', views.send_email_order_in_progress, name='admin.send_email_order_in_progress'),

    #Import Order
    path('GetAllImportOrder', views.get_all_import_order, name='admin.get_all_import_order'),
    path('ImportOrder', views.import_order, name='admin.import_order'),
    path('ViewDetail', views.view_detail, name='admin.view_detail'),   
    path('storeImportOrder', views.store_import_order, name='import_order.post'),
    path('GetAllProduct', views.get_all_product, name='admin.get_all_product'),

    # Order
    path('order', views.order_index, name='admin.order'),
    path('getAllOrder', views.get_all_order, name='admin.get_all_order'),
    path('updateOrder', views.update_order, name='admin.update_order'),
    path('getDetailOrder', views.get_detail_order, name='admin.get_detail_order'),


    #Message
    path('message', views.message, name='admin.message'),
    path('get_all_message', views.get_all_message, name='admin.get_all_message'),
    path('process_message', views.process_message, name='admin.process_message'),
    path('getMessageInProgress', views.get_message_in_progress, name='admin.get_message_in_progress'),

]

svat/apps/users/urls.py
from django.urls import path 
from . import views

urlpatterns = [
    # Top-page
    path('', views.index, name='user.index'),

    # Register
    path('register', views.handle_register, name='user.register'),
    path('register/verify/<str:email>/<str:verify_token>', views.verify_email, name='user.verify_email'),
    path('register/success', views.success_register, name='user.success_register'),
    path('register/re-send-activate', views.resend_activate, name='user.resend_activate'),

    # Login
    path('login', views.handle_login, name='user.login'),
    path('logout', views.handle_logout, name='user.logout'),

    # Forget password
    path('forget-password', views.forget_password, name='user.forget-password'),
    path('forget-password/send-mail', views.forget_password_send_mail, name='user.forget-password-send-mail'),
    path('forget-password/check-secret-token', views.forget_password_check_secret_token, name='user.forget-password-check-secret-token'),
    path('forget-password/change-password', views.forget_password_change_password, name='user.forget-password-change-password'),

    path('product/<int:id>', views.detail_product, name='user.detail_product'),
   
    # Product List
    path('categories', views.get_product_categories, name='user.product_categories'),
    path('product', views.get_product_list, name='user.product.list'),

    # Profile
    path('user/profile', views.view_profile, name='user.view_profile'),
    path('user/updateprofile', views.update_profile, name='user.update_profile'),


    # Articles list
    path('articles', views.get_article_list, name='user.article.list'),

    #Orders
    path('user/orders', views.view_orders, name='user.view_orders'),
    path('user/deleteOrder', views.delete_orders, name='user.delete_orders'),

    # Shopping cart
    path('shopping-cart', views.shopping_cart, name='user.shopping_cart'),
    path('get-shopping-cart', views.get_shopping_cart, name='user.get_shopping_cart'),
    path('add-product-to-cart', views.add_product_to_cart, name='user.add_product_to_cart'),
    path('update-product-to-cart', views.update_product_to_cart, name='user.update_product_to_cart'),
    path('delete-product-to-cart', views.delete_product_to_cart, name='user.delete_product_to_cart'),
    path('checkout-now', views.checkout_now, name='user.checkout_now'),

    # Contact
    path('contact', views.contact, name='user.contact'),
    path('send_message', views.send_message, name='user.send_message'),


    path('checkout', views.checkout, name='user.checkout'),
    
    path('article/<int:id>', views.detail_article, name='user.detail_article'),
]

svat/svat/urls.py
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# i18n_patterns auto detect current language => push language_code to prefix
urlpatterns = i18n_patterns(
    # admin page
    path('admin/', include('apps.my_admin.urls')),

    # user page
    path('', include('apps.users.urls')),
)

# handle for ckeditor upload image
urlpatterns += [
    # Do not delete => django-ckeditor will not work without this
    path('built_in_admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

svat/apps/my_admin/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import AbstractUser
from django.db.models import Sum
import apps.const.const as CONST
from datetime import datetime
from django.db import models
import json



class Media (models.Model):
    class Meta:
        db_table = "media"
    id = models.AutoField(primary_key=True)
    file_path = models.TextField()


class User (AbstractUser):
    class Meta:
        db_table = "users"
        app_label = 'my_admin'
    id = models.AutoField(primary_key=True)
    email = models.CharField(max_length=100, null=False, unique=True)
    name = models.TextField(null=False)
    dob = models.DateTimeField(null=True)
    gender = models.IntegerField(null=True)
    address = models.TextField(null=True,default="")
    phone_number = models.TextField(null=True)
    note = models.TextField(null=True)
    role = models.IntegerField(null=False, default=1)
    verified_token = models.TextField(null=True)
    is_verify = models.IntegerField(null=True, default=0)
    avatar = models.ForeignKey(Media, on_delete=models.CASCADE, null=True)


class Language (models.Model):
    class Meta:
        db_table = "language"
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    code = models.CharField(null=True, max_length=100)


class ProductCategory(models.Model):
    class Meta:
        db_table = "product_category"
    id = models.AutoField(primary_key=True)
    name_en = models.TextField()
    name_vi = models.TextField()


class ArticleCategory(models.Model):
    class Meta:
        db_table = "article_category"
    id = models.AutoField(primary_key=True)
    name_en = models.TextField()
    name_vi = models.TextField()


class Product (models.Model):
    class Meta:
        db_table = "product"
    id = models.AutoField(primary_key=True)
    view = models.IntegerField()
    des = models.TextField()
    is_hide_price = models.IntegerField(null=True, default=0)
    product_category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def product_language_vi(self):
        return self.productlanguage_set.filter(language_id=CONST.LANGUAGE_DICT['vi']).first()

    def product_language_en(self):
        return self.productlanguage_set.filter(language_id=CONST.LANGUAGE_DICT['en']).first()

    def product_images(self):
        return self.productimage_set.all()

    def product_thumbnail(self):
        images = self.productimage_set.all()
        return images[0].media.file_path if len(images) > 0 else ""

    def product_model(self):
        models = self.product_model.all().order_by('price')
        return models

    def min_price_model(self):
        model = self.product_model.all().order_by('price').first()
        if model:
            return model
        return None

    def min_price(self):
        model = self.product_model.all().order_by('price').first()
        if model:
            return model.price
        return 0

    def max_price(self):
        model = self.product_model.all().order_by('price').last()
        if model:
            return model.price
        return 0

    def total_quantity (self):
        total_quantity = self.product_model.aggregate(Sum('quantity'))
        return total_quantity['quantity__sum']


class ProductModel(models.Model):
    class Meta:
        db_table = "product_model"

    id = models.AutoField(primary_key=True)
    weight = models.CharField(max_length=512)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_model")
    quantity = models.IntegerField(default=0)
    
    def __str__(self):
        return json.dumps({
            'id': self.id,
            'weight': self.weight,
            'price': self.price,
            'product': self.product.__str__(),
            'quantity': self.quantity,
        })


class ProductImage (models.Model):
    class Meta:
        db_table = "product_image"
    id = models.AutoField(primary_key=True)
    media = models.ForeignKey(Media, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Article (models.Model):
    class Meta:
        db_table = "article"
    id = models.AutoField(primary_key=True)
    post_at = models.DateTimeField()
    view = models.IntegerField()
    article_category = models.ForeignKey(ArticleCategory, on_delete=models.CASCADE)
    thumbnail = models.ForeignKey(Media, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def article_language_vi (self):
        return self.articlelanguage_set.filter(language_id=CONST.LANGUAGE_DICT['vi']).first()

    def article_language_en (self):
        return self.articlelanguage_set.filter(language_id=CONST.LANGUAGE_DICT['en']).first()


class ArticleLanguage (models.Model):
    class Meta:
        db_table = "article_language"
    id = models.AutoField(primary_key=True)
    title = models.TextField()
    content = RichTextUploadingField(blank=True, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)


class ProductLanguage (models.Model):
    class Meta:
        db_table = "product_language"
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=512)
    des = RichTextUploadingField(blank=True, null=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class Order (models.Model):
    class Meta:
        db_table = "order"
    id = models.AutoField(primary_key=True)
    address = models.CharField(max_length=256)
    name = models.TextField(null=False)
    email = models.CharField(max_length=256)
    phone_number = models.CharField(max_length=256)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    shipping_fee = models.IntegerField(null=False, default=0)
    total_products = models.IntegerField(null=False, default=0) # total product in bill
    total = models.IntegerField(null=False, default=0) # product in bill + shipping fee
    # { Đặt hàng: 0, Xử lý đơn hàng: 1, Vận chuyển: 2, Hoàn Thành: 3, Hủy bỏ: 4 }
    status = models.IntegerField(null=False, default=0) 
    created = models.DateTimeField(default=datetime.now)
    note = models.TextField(null=True)

    def order_product (self):
        return self.orderproduct_set.all()


class OrderProduct (models.Model):
    class Meta:
        db_table = "order_product"
    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField(null=True)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product_model = models.ForeignKey(ProductModel, on_delete=models.CASCADE, null=True)


class ImportOrder (models.Model):
    class Meta:
        db_table = "import_order"
    id = models.AutoField(primary_key=True)
    created = models.DateTimeField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)


class ImportOrderProduct (models.Model):
    class Meta:
        db_table = "import_order_product"
    id = models.AutoField(primary_key=True)
    quantity = models.IntegerField()
    import_order = models.ForeignKey(ImportOrder, on_delete=models.CASCADE)
    product_model = models.ForeignKey(ProductModel, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return json.dumps({
            'id', self.id,
            'quantity', self.quantity,
            'product_model', self.product_model.__str__(),
        })

class Message (models.Model):
    class Meta:
        db_table = "message"
    id = models.AutoField(primary_key=True)
    name = models.TextField(null=False)
    email = models.CharField(max_length=256)
    message = models.CharField(max_length=256)
    status=models.IntegerField(null=False, default=0)
    created = models.DateTimeField(default=datetime.now)

svat/apps/users/models.py
from django.db import models

# Create your models here.

svat/apps/my_admin/forms.py
from django import forms
from apps.my_admin.models import ArticleLanguage, ProductLanguage

class ArticleForm(forms.ModelForm):
    class Meta:
        model = ArticleLanguage
        fields = ('content', )
        labels = {
            "content": ""
        }


class ProductForm(forms.ModelForm):
    class Meta:
        model = ProductLanguage
        fields = ('des', )
        labels = {
            "des": ""
        }

svat/apps/my_admin/templates/pages/dashboard.html
{% extends 'layout/base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<section class="content pt-4">
      <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-info">
              <div class="inner">
		      <h3>{{total_order}}</h3>

                <p>Đơn hàng</p>
              </div>
              <div class="icon">
                <i class="ion ion-bag"></i>
              </div>
	      <a href="{% url 'admin.order' %}" class="small-box-footer">Thêm thông tin<i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-success">
              <div class="inner">
	      <h3>{{total_product}}</h3>

                <p>Sản phẩm</p>
              </div>
              <div class="icon">
                <i class="ion ion-stats-bars"></i>
              </div>
              <a href="{% url 'admin.product' %}" class="small-box-footer">Thêm thông tin<i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-warning">
              <div class="inner">

	      <h3>{{total_user}}</h3>

                <p>User</p>
              </div>
              <div class="icon">
                <i class="ion ion-person-add"></i>
              </div>
              <a href="{% url 'admin.user' %}" class="small-box-footer">Thêm thông tin<i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <!-- small box -->
            <div class="small-box bg-danger">
              <div class="inner">
	      <h3>{{total_feed_back}}</h3>

                <p>Phản hồi</p>
              </div>
              <div class="icon">
                <i class="ion ion-pie-graph"></i>
              </div>
              <a href="{% url 'admin.message' %}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
            </div>
          </div> <!-- ./col --> </div> <!-- /.row -->
        <!-- Main row -->
	<div class="row w-100">
		<div class="card col-12 p-0 m-3">
              <div class="card-header ui-sortable-handle w-100" style="cursor: move;">
                <h3 class="card-title m-0">
                  <i class="fas fa-chart-pie mr-1"></i>
                  Thống kê sản phẩm bán ra 
                </h3>
              </div><!-- /.card-header -->
              <div class="card-body">
                <div class="tab-content p-0">
                  <!-- Morris chart - Sales -->
                  <div class="chart tab-pane active" id="revenue-chart" style="position: relative; height: 300px;"><div class="chartjs-size-monitor"><div class="chartjs-size-monitor-expand"><div class=""></div></div><div class="chartjs-size-monitor-shrink"><div class=""></div></div></div>
                      <canvas id="donutChart" height="300" style="height: 300px; display: block; width: 512px;" width="512" class="chartjs-render-monitor"></canvas>
                   </div>
                </div>
              </div><!-- /.card-body -->
            </div>
	</div>
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
{% endblock content %}
{% block script  %}
<!-- ChartJS -->
<script src="{% static 'admin-lte/plugins/chart.js/Chart.min.js' %}"></script>
<script>
    var donutChartCanvas = $('#donutChart').get(0).getContext('2d')
    var donutData        = {
      labels: [
	  {% for category in list_category %}
	      '{{category.product_category__name_vi}}',
	   {% endfor  %}
      ],
      datasets: [
        {
          data: [
	   {% for category in list_category %}
	      parseInt('{{category.total}}'),
	   {% endfor  %}
	  ],
          backgroundColor : ['#f56954', '#00a65a', '#f39c12', '#00c0ef', '#3c8dbc', '#d2d6de'],
        }
      ]
    }
    var donutOptions     = {
      maintainAspectRatio : false,
      responsive : true,
    }
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    new Chart(donutChartCanvas, {
      type: 'doughnut',
      data: donutData,
      options: donutOptions
    })

    //-------------
    //- PIE CHART -
    //-------------
    // Get context with jQuery - using jQuery's .get() method.
    var pieChartCanvas = $('#pieChart').get(0).getContext('2d')
    var pieData        = donutData;
    var pieOptions     = {
      maintainAspectRatio : false,
      responsive : true,
    }
    //Create pie or douhnut chart
    // You can switch between pie and douhnut using the method below.
    new Chart(pieChartCanvas, {
      type: 'pie',
      data: pieData,
      options: pieOptions
    })

</script>
{% endblock script  %}

svat/apps/my_admin/templates/pages/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" type="image/jpg" href="{% static 'user/global/images/logo.png' %}"/>
  <title>Admin login</title>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'admin-lte/dist/css/adminlte.min.css' %}">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <!-- /.login-logo -->
  <div class="card card-outline card-primary">
    <div class="card-header text-center">
      <a href="#" class="h1"><b>Admin</b></a>
    </div>
    <div class="card-body">
      <p class="login-box-msg">Đăng nhập để bắt đầu phiên làm việc</p>

      <form action="{% url 'admin.login' %}" method="post">
        {% csrf_token %}
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}} 
        </div>
        {% endif %}
        <div class="input-group mb-3">
          <input type="email" class="form-control" name="email" placeholder="Email" autocomplete="chrome-off">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" name="password" placeholder="Password" autocomplete="chrome-off">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="d-flex justify-content-end">
          <button type="submit" class="btn btn-primary">Đăng nhập</button>
        </div>
      </form>

      {% comment %} <div class="social-auth-links text-center mt-2 mb-3">
        <a href="#" class="btn btn-block btn-primary">
          <i class="fab fa-facebook mr-2"></i> Sign in using Facebook
        </a>
        <a href="#" class="btn btn-block btn-danger">
          <i class="fab fa-google-plus mr-2"></i> Sign in using Google+
        </a>
      </div> {% endcomment %}
      <!-- /.social-auth-links -->

     
    </div>
    <!-- /.card-body -->
  </div>
  <!-- /.card -->
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'admin-lte/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'admin-lte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src"{% static 'admin-lte/dist/js/adminlte.min.js' %}"></script>
</body>
</html>

svat/apps/my_admin/templates/pages/message.html
{% extends 'layout/base.html' %}
{% load static %}
{% block css %}
{% endblock css %}
{% block content %}

<style>
  .dataTables_filter{
    float: left !important;
  }
  .disableRow{
    background: #d4d4d4 !important;
  }

  /* table general */
  th:first-child {
    width:1%;
    white-space: nowrap;
  }

  td:last-child {
    white-space: nowrap;
    width: 1%;
  }

  td:last-child button:first-child {
    margin-right: 10px;
  }
</style>
<div class="content container-fluid" style="padding: 1rem">

<div class="row p-2">
  <div class="col"><h3>Phản hồi khách hàng</h3></div>
  <div class="col"></div>
</div>

<div class="modal fade" id="warningModal" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cảnh báo</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p id="id_message" style="display: none;"></p>
        <p>Phản hồi bị chuyển trạng thái sang <mark>Đã xử lý</mark> Bạn sẽ không thể thay đổi trạng thái nữa. Bạn có chắc muốn tiếp tục?</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
        <button type="button" class="btn btn-primary" id="confirmUpdate">Cập nhật</button>
      </div>
    </div>
  </div>
</div>

  <div class="card card-primary card-outline">
    <div class="card-body">
      <table id="all_message" class="table table-bordered table-hover table-fixed" style="width:100%">
        <thead>
          <tr>
            <th>Id<nav></nav></th>
              <th>Họ tên<nav></nav></th>
              <th>Email</th>
              <th>Nội dung</th>
              <th>Thời gian</th>
              <th>Thao tác</th>
          </tr>
      </thead>
        </table>
      </div>
    </div>
</div>

{% endblock content %}
{% block script %}
<script>
    function addLeadingZero(strDate){
      return ('0' + strDate.toString()).slice(-2)
    }

    function formatDate(date, includedTime=false){
        let dateStr = `${addLeadingZero(date.getUTCDate())}/${addLeadingZero(date.getUTCMonth() + 1)}/${date.getUTCFullYear()}`
        let timeStr = ''

        if(includedTime === true){
            timeStr = `${addLeadingZero((date.getUTCHours() + 7) % 24)}:${addLeadingZero(date.getUTCMinutes())}:${addLeadingZero(date.getUTCSeconds())}`
        }
        
        return `${dateStr} ${timeStr}`
    }
    
    var tableMessage = $('#all_message').DataTable({
        "serverSide": true,
        "ajax": {
            url: "/en/admin/get_all_message",
            type: "GET"
        },
        "pageLength": 20,
        "searchDelay": 500,
        "bLengthChange": false,
        "ordering": false,
        "createdRow": function( row, data, dataIndex){
          if( data.status ==  1 ){
            $(row).addClass('disableRow');
          }
        },
        "columns": [
            { "data": "id" },
            { "data": "name" },
            { "data": "email" },
            { "data": "message" },
            {
              "data": "created",
              "render": function(data, type, row, meta){
                if(data === null) return ''
                let date = new Date(data)
                return formatDate(date, true)
              }
            },
            {
              "data": "actions",
              "render": function ( data, type, row, meta ) {
                let btnUpdate = $('<button class="btn btn-success update-btn"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-check-lg" viewBox="0 0 16 16"> <path d="M13.485 1.431a1.473 1.473 0 0 1 2.104 2.062l-7.84 9.801a1.473 1.473 0 0 1-2.12.04L.431 8.138a1.473 1.473 0 0 1 2.084-2.083l4.111 4.112 6.82-8.69a.486.486 0 0 1 .04-.045z"/> </svg></button>')
                if (row.status == 1 ) btnUpdate.attr('disabled', true)
                return `${btnUpdate[0].outerHTML} `

              }
            }

        ]
    });

    $(document).on('click', '.update-btn', function(){
      messageRow = $(this).parents('tr')[0]
      message = tableMessage.row(messageRow).data()
      $('#warningModal').modal('show')
      $("#id_message").val(message.id)
    })

    $(document).on('click', '#confirmUpdate', function(){
      $('#warningModal').modal('hide')

      let data={
        id: $("#id_message").val(),
      }

      let url = `/${window.location.pathname.split('/')[1]}/admin/process_message`;

      $.ajax({
          url,
          type: "POST",
          headers: {
            "X-CSRFTOKEN": $("[name=csrfmiddlewaretoken]").val()
          },
          dataType: 'json',
          processData: false,
          contentType: 'application/json; charset=utf-8',
          data: JSON.stringify(data),
          success: function(data) {
            toastr.success('Cập nhật trạng thái thành công')
            setTimeout(function(){
                                window.location.reload(true);
                            }, 2000);
          }
      })
    })


</script>
{% endblock script %}
 